# Generated by Django 3.1.4 on 2021-02-02 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='message',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='info',
            old_name='subject',
            new_name='place',
        ),
    ]
