# Generated by Django 3.1.4 on 2021-02-04 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20210202_1841'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='info',
            options={'verbose_name': 'Info', 'verbose_name_plural': 'Infos'},
        ),
    ]
